site_name: Phenox Library Documentation
theme: readthedocs
#repo_url: https://github.com/phenoxlab/phenox/
repo_url: https://github.com/mthrok/phenox/
site_description: Phenox Library Documentation
site_author: Ryo Konomura
site_favicon: 'favicon.ico'
site_dir: '../../site-doc/en'
pages:
- 'Home': 'home.md'
- 'Index': 'index.md'
- 'Training': 'training.md'