site_name: Phenox Library Documentation
theme: readthedocs
#repo_url: https://github.com/phenoxlab/phenox/
repo_url: https://github.com/mthrok/phenox/
site_description: Phenox Library Documentation
site_author: 此村 領
site_favicon: 'favicon.ico'
site_dir: '../../site-doc/ja'
pages:
- 'ホーム': 'home.md'
- 初めに:
    - '初めにお読みください': '01/note.md'
    - 'Phenox セット内容物': '01/package.md'
    - '機体構成': '01/hardware.md'
    - '回路構成': '01/circuit.md'
    - '機体軸と回転方向': '01/directions.md'
    - '電源について': '01/power.md'
    - '通信方法について': '01/com.md'
    - 'その他の取り扱い': '01/others.md'
- アプリケーション開発:
    - '開発について': '02/dev.md'
    - 'Linux 環境の構築': '02/env.md'
    - 'Phenox ライブラリについて': '02/about_library.md'
    - 'API' : '02/api_ref.md'
- 'トラブルシューティング': 'trouble_shooting.md'
